package main

import (
	"context"
	"database/sql"
	"fmt"

	cnsdpdb "cnsdp/internal/db"
)

// readOnlyRole is a role the harness creates for itself in the isolated
// cnsdp-verify Postgres instance, distinct from the app's own privileged
// "cnsdp" role. Every query this harness issues after setup uses this
// role's own connection -- SELECT-only, enforced by Postgres itself (see
// VerifyReadOnlyEnforced), not merely by convention in the Go code that
// happens to only call query methods.
const readOnlyRole = "cnsdp_verify_reader"

// SetupReadOnlyAccess bootstraps a SELECT-only role in the isolated
// cnsdp-verify Postgres instance (using the app's own privileged
// credentials for this one bootstrap step only, over a connection that is
// closed immediately afterward) and returns a *sql.DB authenticated as
// that role. All product-table mutation happens exclusively through
// APIClient.PostAuditEvent -- the real HTTP intake path -- never through
// this connection.
func SetupReadOnlyAccess(ctx context.Context, postgresHostPort, adminPassword string) (*sql.DB, error) {
	roPassword, err := randomHex(32)
	if err != nil {
		return nil, wrapEnvErr("generate read-only role password", err)
	}

	// adminPassword and roPassword are both generated by randomHex, i.e.
	// drawn from a fixed [0-9a-f] alphabet -- direct interpolation into a
	// single-quoted SQL literal below is safe by construction (no quote,
	// backslash, or other special character can ever appear), and
	// PostgreSQL's CREATE ROLE/GRANT DDL statements do not accept
	// parameterized placeholders for identifiers or literals in any case.
	privilegedDSN := fmt.Sprintf("postgres://cnsdp:%s@127.0.0.1:%s/cnsdp?sslmode=disable", adminPassword, postgresHostPort)
	if err := bootstrapReadOnlyRole(ctx, privilegedDSN, roPassword); err != nil {
		return nil, err
	}

	readOnlyDSN := fmt.Sprintf("postgres://%s:%s@127.0.0.1:%s/cnsdp?sslmode=disable", readOnlyRole, roPassword, postgresHostPort)
	conn, err := cnsdpdb.Connect(ctx, readOnlyDSN)
	if err != nil {
		return nil, wrapEnvErr("connect as read-only role", err)
	}

	if err := VerifyReadOnlyEnforced(ctx, conn); err != nil {
		conn.Close()
		return nil, err
	}

	return conn, nil
}

func bootstrapReadOnlyRole(ctx context.Context, privilegedDSN, roPassword string) error {
	conn, err := cnsdpdb.Connect(ctx, privilegedDSN)
	if err != nil {
		return wrapEnvErr("connect with privileged role to bootstrap read-only role", err)
	}
	defer conn.Close()

	stmts := []string{
		fmt.Sprintf(`DO $$ BEGIN
			IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '%s') THEN
				CREATE ROLE %s LOGIN PASSWORD '%s';
			END IF;
		END $$;`, readOnlyRole, readOnlyRole, roPassword),
		fmt.Sprintf(`GRANT CONNECT ON DATABASE cnsdp TO %s;`, readOnlyRole),
		fmt.Sprintf(`GRANT USAGE ON SCHEMA public TO %s;`, readOnlyRole),
		fmt.Sprintf(`GRANT SELECT ON ALL TABLES IN SCHEMA public TO %s;`, readOnlyRole),
		fmt.Sprintf(`ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO %s;`, readOnlyRole),
	}
	for _, stmt := range stmts {
		if _, err := conn.ExecContext(ctx, stmt); err != nil {
			return wrapEnvErr("bootstrap read-only role", fmt.Errorf("executing %q: %w", stmt, err))
		}
	}
	return nil
}

// VerifyReadOnlyEnforced proves, at runtime, that the harness's own
// database role genuinely cannot write -- not merely that the Go code
// happens not to call a write method. The attempted statement matches
// zero rows even in the (expected-not-to-happen) case it were permitted,
// and the transaction is rolled back unconditionally either way.
func VerifyReadOnlyEnforced(ctx context.Context, roConn *sql.DB) error {
	tx, err := roConn.BeginTx(ctx, nil)
	if err != nil {
		return wrapEnvErr("verify read-only role", err)
	}
	defer tx.Rollback()

	_, execErr := tx.ExecContext(ctx, `UPDATE submissions SET audit_stage = audit_stage WHERE false`)
	if execErr == nil {
		return envErrorf("verify read-only role", "role %s was able to execute a write statement -- refusing to proceed with an unenforced read-only role", readOnlyRole)
	}
	return nil
}
